### PR TITLE
Shortest path now uses algorithm

### PR DESCRIPTION
**Pull request by TheCoolBoss**
- Shortest path uses the algorithm now.
- Since the only difference between the 2 graphs is weight, I introduced a boolean parameter that determines which weight to use. The intent is to avoid duplicating methods that only have 1 different line.
- Added a distance calculator based on Haversine formula (see Discord).
- Removed the SomeClass service since we don't need it anymore.

### CODE REVIEW

**Review by dshaur — APPROVED** [review]
Looks really good! I was able to find different routes using both search types (shortest and cheapest).

**Review by dnguyen09 — APPROVED** [review]
The implementation of the shortest path algorithm working well to me. However, I'm unsure if it makes sense because when I tested a flight from Tokyo to Lima, the shortest flight returned the same route and price as the cheapest flight.

**Comment by dshaur** [comment]
> The implementation of the shortest path algorithm working well to me. However, I'm unsure if it makes sense because when I tested a flight from Tokyo to Lima, the shortest flight returned the same route and price as the cheapest flight.

This is because there is no direct flight from Tokyo to Lima (it doesnt exist in real life). The only way to get to Lima from Tokyo is through Mexico in this case, since there is no other airport close by in the context of our database.

**Review by JuicingJuicer — APPROVED** [review]
Looks good

**Pull request merged**
