### PR TITLE
Added MySQL Database Schema

### PR DESCRIPTION
**Pull request by dshaur**
# Database

* Created database and script files for the remote mysql server. 

* Added the database schema, data insertion and updated flight prices using the Haversine formula for a realistic approach.

## Haversine formula

The Haversine formula is used to calculate the distance between two points on the Earth's surface based on their latitude and longitude coordinates. It provides an approximation of the distance between the points assuming the Earth is a perfect sphere.

Here's a simple explanation of how the formula works:

* The formula begins by converting the latitude and longitude values of the two points into radians. This conversion is necessary because trigonometric functions operate on radians.

* It then calculates the differences between the latitudes and longitudes of the two points.

* The formula uses the haversine function, which is a trigonometric function, to calculate the square of half the chord length between the points. This value represents the central angle between the points on the sphere.

* The haversine function takes the squares of the differences in latitude and longitude, divides them by 2, and calculates their sum. It accounts for the curvature of the Earth's surface in this step.

* The formula uses the inverse sine (ASIN) function to calculate the arcsine of the square root of the central angle. This step retrieves the actual central angle between the points.

* The central angle is then multiplied by the Earth's radius (assumed to be 6371 kilometers) to obtain the distance between the points on the Earth's surface.

That's a simplified explanation of the Haversine formula. It provides a way to estimate distances between points given their latitude and longitude coordinates.

## Files involved

* `sz_flightfinder.sql` (Schema script)
* `insert_queries.sql` (Data insertion script)
* `flight_price_formula.sql` (Prices were assigned at random during data insertion queries. This UPDATE query implements the Haversine formula for realistic pricing based on distance. Added a flat fee of $75 to the formula in order for the price to be as realistic as possible)
* `big_join_query.sql` (For visualization)

### CODE REVIEW

**Review by dnguyen09 — APPROVED** [review]
looks good

**Review by TheCoolBoss — APPROVED** [review]
Looks good

**Review by JuicingJuicer — APPROVED** [review]
Looks good

**Review by IsraelHG — APPROVED** [review]
Great! LGTM :octocat:

**Pull request merged**
