### PR TITLE
Added models w/ its relations of other models

### PR DESCRIPTION
**Pull request by IsraelHG**
Models included are:
- Airline
- Airport
- City
- Country
- Flight

Along with their relations based on the database.

### CODE REVIEW

**Review by TheCoolBoss — APPROVED** [review]
Looks good

**Review by JuicingJuicer — APPROVED** [review]
Looks good

**Review by dnguyen09 — APPROVED** [review]
everything looks good

**Review by dshaur — APPROVED** [review]
I like it. Good job!

**Pull request merged**
